window:
  width: 800
  height: 600
  vsync: true
  # Only applied for fullscreen, overrides the current resolution
  maximize: true
  retina: true   # For retina displays
  # WINDOWED            = 0
  # FULLSCREEN          = 1
  # WINDOWED FULSCREEN  = 2
  window-mode: 1
  monitor: 0 # Monitor to be displayed on