window:
  width: 1280
  height: 720
  vsync: true
  # Only applied for fullscreen, overrides the current resolution
  retina: true   # For retina displays
  # WINDOWED            = 0
  # FULLSCREEN          = 1
  # WINDOWED FULSCREEN  = 2
  window-mode: 0
  maximize: false
  monitor: 0 # Monitor to be displayed on